feat: Add feature to separate doctor module

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,8 +2,16 @@ echo 'Please be patient, this may take a while'
 
 echo 'First, lets check the code style or linting errors 🎨'
 
+echo ''
 npx lint-staged || {
   echo 'Linting failed, please fix the errors and try again'
+  exit 1
+}
+
+echo ''
+echo 'Checking TypeScript type errors 🧐'
+npx tsc --noEmit || {
+  echo 'Type checking failed, please fix the errors and try again'
   exit 1
 }
 
